# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rm_pb2 as rm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbackend.proto\x1a\x08rm.proto2K\n\x0f\x42\x61\x63kEndServicer\x12\x38\n\x13GetInferenceRequest\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[rm__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BACKENDSERVICER = _descriptor.ServiceDescriptor(
  name='BackEndServicer',
  full_name='BackEndServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=27,
  serialized_end=102,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInferenceRequest',
    full_name='BackEndServicer.GetInferenceRequest',
    index=0,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKENDSERVICER)

DESCRIPTOR.services_by_name['BackEndServicer'] = _BACKENDSERVICER

# @@protoc_insertion_point(module_scope)
