# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rm_pb2 as rm__pb2


class BackEndServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInferenceRequest = channel.unary_unary(
                '/BackEndServicer/GetInferenceRequest',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )


class BackEndServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInferenceRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackEndServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInferenceRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceRequest,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BackEndServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BackEndServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInferenceRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BackEndServicer/GetInferenceRequest',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
