# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rm_pb2 as rm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='frontend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x66rontend.proto\x1a\x08rm.proto2G\n\x10\x46rontEndServicer\x12\x33\n\x0eGetPredictions\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[rm__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FRONTENDSERVICER = _descriptor.ServiceDescriptor(
  name='FrontEndServicer',
  full_name='FrontEndServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=28,
  serialized_end=99,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPredictions',
    full_name='FrontEndServicer.GetPredictions',
    index=0,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRONTENDSERVICER)

DESCRIPTOR.services_by_name['FrontEndServicer'] = _FRONTENDSERVICER

# @@protoc_insertion_point(module_scope)
