# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rm_pb2 as rm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08nm.proto\x1a\x08rm.proto2\xab\x02\n\x08NMServer\x12.\n\tLaunchJob\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12\x31\n\x0cTerminateJob\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12,\n\nGetMetrics\x12\r.JsonResponse\x1a\r.JsonResponse\"\x00\x12/\n\nSetMetrics\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12-\n\x08GetLease\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12.\n\x0fNotifyTerminate\x12\x07.IntVal\x1a\x10.BooleanResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[rm__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_NMSERVER = _descriptor.ServiceDescriptor(
  name='NMServer',
  full_name='NMServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=23,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='LaunchJob',
    full_name='NMServer.LaunchJob',
    index=0,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TerminateJob',
    full_name='NMServer.TerminateJob',
    index=1,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMetrics',
    full_name='NMServer.GetMetrics',
    index=2,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetMetrics',
    full_name='NMServer.SetMetrics',
    index=3,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLease',
    full_name='NMServer.GetLease',
    index=4,
    containing_service=None,
    input_type=rm__pb2._JSONRESPONSE,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NotifyTerminate',
    full_name='NMServer.NotifyTerminate',
    index=5,
    containing_service=None,
    input_type=rm__pb2._INTVAL,
    output_type=rm__pb2._BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NMSERVER)

DESCRIPTOR.services_by_name['NMServer'] = _NMSERVER

# @@protoc_insertion_point(module_scope)
