# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rm_pb2 as rm__pb2


class NMServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LaunchJob = channel.unary_unary(
                '/NMServer/LaunchJob',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )
        self.TerminateJob = channel.unary_unary(
                '/NMServer/TerminateJob',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/NMServer/GetMetrics',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.JsonResponse.FromString,
                )
        self.SetMetrics = channel.unary_unary(
                '/NMServer/SetMetrics',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )
        self.GetLease = channel.unary_unary(
                '/NMServer/GetLease',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )
        self.NotifyTerminate = channel.unary_unary(
                '/NMServer/NotifyTerminate',
                request_serializer=rm__pb2.IntVal.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )


class NMServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LaunchJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyTerminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NMServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LaunchJob': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchJob,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
            'TerminateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateJob,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.JsonResponse.SerializeToString,
            ),
            'SetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMetrics,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
            'GetLease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLease,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
            'NotifyTerminate': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyTerminate,
                    request_deserializer=rm__pb2.IntVal.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NMServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NMServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LaunchJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NMServer/LaunchJob',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NMServer/TerminateJob',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NMServer/GetMetrics',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NMServer/SetMetrics',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NMServer/GetLease',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyTerminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NMServer/NotifyTerminate',
            rm__pb2.IntVal.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
