# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rm_pb2 as rm__pb2


class RMServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/RMServer/RegisterWorker',
                request_serializer=rm__pb2.RegisterRequest.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )
        self.AcceptJob = channel.unary_unary(
                '/RMServer/AcceptJob',
                request_serializer=rm__pb2.JsonResponse.SerializeToString,
                response_deserializer=rm__pb2.BooleanResponse.FromString,
                )
        self.ReturnTime = channel.unary_unary(
                '/RMServer/ReturnTime',
                request_serializer=rm__pb2.EmptyMsg.SerializeToString,
                response_deserializer=rm__pb2.IntVal.FromString,
                )


class RMServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Node Manager calls registers with resource manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RMServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=rm__pb2.RegisterRequest.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
            'AcceptJob': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptJob,
                    request_deserializer=rm__pb2.JsonResponse.FromString,
                    response_serializer=rm__pb2.BooleanResponse.SerializeToString,
            ),
            'ReturnTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnTime,
                    request_deserializer=rm__pb2.EmptyMsg.FromString,
                    response_serializer=rm__pb2.IntVal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RMServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RMServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RMServer/RegisterWorker',
            rm__pb2.RegisterRequest.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RMServer/AcceptJob',
            rm__pb2.JsonResponse.SerializeToString,
            rm__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReturnTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RMServer/ReturnTime',
            rm__pb2.EmptyMsg.SerializeToString,
            rm__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
