# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08rm.proto\" \n\x0cJsonResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\xdc\x01\n\x0fRegisterRequest\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x0f\n\x07numGPUs\x18\x02 \x01(\x05\x12\x13\n\x0bnumCPUcores\x18\x03 \x01(\x05\x12\x16\n\x0ememoryCapacity\x18\x04 \x01(\x05\x12\x15\n\rnumaAvailable\x18\x05 \x01(\x08\x12\x32\n\tcpuMaping\x18\x06 \x03(\x0b\x32\x1f.RegisterRequest.CpuMapingEntry\x1a\x30\n\x0e\x43puMapingEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\" \n\x0f\x42ooleanResponse\x12\r\n\x05value\x18\x01 \x01(\x08\"\x17\n\x06IntVal\x12\r\n\x05value\x18\x01 \x01(\x05\"\n\n\x08\x45mptyMsg2\x96\x01\n\x08RMServer\x12\x36\n\x0eRegisterWorker\x12\x10.RegisterRequest\x1a\x10.BooleanResponse\"\x00\x12.\n\tAcceptJob\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12\"\n\nReturnTime\x12\t.EmptyMsg\x1a\x07.IntVal\"\x00\x62\x06proto3'
)




_JSONRESPONSE = _descriptor.Descriptor(
  name='JsonResponse',
  full_name='JsonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='JsonResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=44,
)


_REGISTERREQUEST_CPUMAPINGENTRY = _descriptor.Descriptor(
  name='CpuMapingEntry',
  full_name='RegisterRequest.CpuMapingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RegisterRequest.CpuMapingEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='RegisterRequest.CpuMapingEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=267,
)

_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ipaddr', full_name='RegisterRequest.ipaddr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numGPUs', full_name='RegisterRequest.numGPUs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numCPUcores', full_name='RegisterRequest.numCPUcores', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memoryCapacity', full_name='RegisterRequest.memoryCapacity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numaAvailable', full_name='RegisterRequest.numaAvailable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpuMaping', full_name='RegisterRequest.cpuMaping', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERREQUEST_CPUMAPINGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=267,
)


_BOOLEANRESPONSE = _descriptor.Descriptor(
  name='BooleanResponse',
  full_name='BooleanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='BooleanResponse.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=301,
)


_INTVAL = _descriptor.Descriptor(
  name='IntVal',
  full_name='IntVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IntVal.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=326,
)


_EMPTYMSG = _descriptor.Descriptor(
  name='EmptyMsg',
  full_name='EmptyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=338,
)

_REGISTERREQUEST_CPUMAPINGENTRY.containing_type = _REGISTERREQUEST
_REGISTERREQUEST.fields_by_name['cpuMaping'].message_type = _REGISTERREQUEST_CPUMAPINGENTRY
DESCRIPTOR.message_types_by_name['JsonResponse'] = _JSONRESPONSE
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['BooleanResponse'] = _BOOLEANRESPONSE
DESCRIPTOR.message_types_by_name['IntVal'] = _INTVAL
DESCRIPTOR.message_types_by_name['EmptyMsg'] = _EMPTYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JsonResponse = _reflection.GeneratedProtocolMessageType('JsonResponse', (_message.Message,), {
  'DESCRIPTOR' : _JSONRESPONSE,
  '__module__' : 'rm_pb2'
  # @@protoc_insertion_point(class_scope:JsonResponse)
  })
_sym_db.RegisterMessage(JsonResponse)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {

  'CpuMapingEntry' : _reflection.GeneratedProtocolMessageType('CpuMapingEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERREQUEST_CPUMAPINGENTRY,
    '__module__' : 'rm_pb2'
    # @@protoc_insertion_point(class_scope:RegisterRequest.CpuMapingEntry)
    })
  ,
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'rm_pb2'
  # @@protoc_insertion_point(class_scope:RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)
_sym_db.RegisterMessage(RegisterRequest.CpuMapingEntry)

BooleanResponse = _reflection.GeneratedProtocolMessageType('BooleanResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEANRESPONSE,
  '__module__' : 'rm_pb2'
  # @@protoc_insertion_point(class_scope:BooleanResponse)
  })
_sym_db.RegisterMessage(BooleanResponse)

IntVal = _reflection.GeneratedProtocolMessageType('IntVal', (_message.Message,), {
  'DESCRIPTOR' : _INTVAL,
  '__module__' : 'rm_pb2'
  # @@protoc_insertion_point(class_scope:IntVal)
  })
_sym_db.RegisterMessage(IntVal)

EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMSG,
  '__module__' : 'rm_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMsg)
  })
_sym_db.RegisterMessage(EmptyMsg)


_REGISTERREQUEST_CPUMAPINGENTRY._options = None

_RMSERVER = _descriptor.ServiceDescriptor(
  name='RMServer',
  full_name='RMServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=341,
  serialized_end=491,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterWorker',
    full_name='RMServer.RegisterWorker',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AcceptJob',
    full_name='RMServer.AcceptJob',
    index=1,
    containing_service=None,
    input_type=_JSONRESPONSE,
    output_type=_BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnTime',
    full_name='RMServer.ReturnTime',
    index=2,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RMSERVER)

DESCRIPTOR.services_by_name['RMServer'] = _RMSERVER

# @@protoc_insertion_point(module_scope)
