# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rm_pb2 as rm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsimulator.proto\x1a\x08rm.proto2W\n\tSimServer\x12#\n\x07GetJobs\x12\x07.IntVal\x1a\r.JsonResponse\"\x00\x12%\n\tGetConfig\x12\x07.IntVal\x1a\r.JsonResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[rm__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SIMSERVER = _descriptor.ServiceDescriptor(
  name='SimServer',
  full_name='SimServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=29,
  serialized_end=116,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetJobs',
    full_name='SimServer.GetJobs',
    index=0,
    containing_service=None,
    input_type=rm__pb2._INTVAL,
    output_type=rm__pb2._JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetConfig',
    full_name='SimServer.GetConfig',
    index=1,
    containing_service=None,
    input_type=rm__pb2._INTVAL,
    output_type=rm__pb2._JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMSERVER)

DESCRIPTOR.services_by_name['SimServer'] = _SIMSERVER

# @@protoc_insertion_point(module_scope)
