# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rm_pb2 as rm__pb2


class SimServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJobs = channel.unary_unary(
                '/SimServer/GetJobs',
                request_serializer=rm__pb2.IntVal.SerializeToString,
                response_deserializer=rm__pb2.JsonResponse.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/SimServer/GetConfig',
                request_serializer=rm__pb2.IntVal.SerializeToString,
                response_deserializer=rm__pb2.JsonResponse.FromString,
                )


class SimServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobs,
                    request_deserializer=rm__pb2.IntVal.FromString,
                    response_serializer=rm__pb2.JsonResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=rm__pb2.IntVal.FromString,
                    response_serializer=rm__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimServer/GetJobs',
            rm__pb2.IntVal.SerializeToString,
            rm__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimServer/GetConfig',
            rm__pb2.IntVal.SerializeToString,
            rm__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
